import React, { useMemo, useState } from 'react';
import { ArrowUpRight, Code2, Gamepad2, Mountain, Mail, MapPin, Sparkles, BriefcaseBusiness, GraduationCap } from 'lucide-react';
import './App.css';

const profile = {
  name: 'Alexander Haas',
  title: 'Gameplay Programmer • Software Engineer • Outdoor Trip Leader',
  location: 'Los Angeles, CA',
  email: 'alexanderhaas1192@gmail.com',
  github: 'https://github.com/AlexH1192',
  linkedin: 'https://www.linkedin.com/in/alexander-haas-865710347/',
  resumeUrl: '#',
  summary: 'M.S. Computer Science student focused on game development, gameplay systems, AI behavior, and technical design. I also lead outdoor climbing trips and bring the same systems thinking, reliability, and risk management mindset to team-based outdoor environments.',
};

const gameProjects = [
  { title: 'Mech-Believe: Mega Brawl', role: 'Enemy AI and Systems Engineer', timeframe: '2025–Present', tags: ['Unity','C#','Enemy AI','Combat Systems','FSM'], summary: 'Competitive robot battler featuring modular mech customization, real-time combat, and enemy decision logic.', bullets: ['Designed and implemented enemy AI using finite state machines and behavior-driven decision logic.','Built combat systems supporting targeting, ability prioritization, dynamic difficulty, and modular robot parts.','Collaborated with design and QA teammates to tune encounter readability, combat pacing, and player experience.'], links: [] },
  { title: 'Purr Force: Scratch and Rescue', role: 'Lead Programmer / Game Design Intern, IndieCade', timeframe: 'May–July 2025', tags: ['Unity','C#','Strategy','Systems Design','AI'], summary: 'Climate-focused grid strategy game selected for the IndieCade Climate Anthology after placing Top 10 overall in the Climate Jam.', bullets: ['Led gameplay engineering on an 8-person team under rapid production constraints.','Architected tile-state systems, action point economy, fire propagation logic, and firefighter ability framework.','Implemented modular AI behaviors and helped translate design goals into readable, playable systems.'], links: [{label:'Add project link', href:'#'}] },
  { title: 'Voiceborne', role: 'Unity Engineer', timeframe: 'Spring 2025', tags: ['Unity','C#','2D Platformer','Audio Input','AI'], summary: '2D action platformer built by a 3-person team, centered on a microphone-driven light and stealth mechanic.', bullets: ['Served as sole gameplay engineer, implementing combat, enemy AI, animation state control, and scene transitions.','Built a real-time microphone loudness system that dynamically modified visibility and detection radius.','Optimized continuous audio input processing to keep the mechanic responsive during gameplay.'], links: [] },
  { title: 'On the Brink', role: 'Lead Unity Developer', timeframe: '2022–2023', tags: ['Unity','C#','Steam','Combat','AI'], summary: 'Student game project published on Steam with 250+ downloads, 1,500+ library additions, and a positive user rating.', bullets: ['Led engineering on a 28-person interdisciplinary team and authored approximately 10,000 lines of C#.','Implemented core combat systems, AI behavior, and player progression mechanics.','Coordinated technical implementation across design, art, and production constraints.'], links: [{label:'Add Steam link', href:'#'}] },
];

const softwareProjects = [
  { title: 'Game Engine Development Project', role: 'CSCI 522 Project Skeleton', timeframe: 'Spring 2026', tags: ['C++','Game Engine','Rendering','Systems','Tools'], summary: 'Placeholder for your game engine class project. Replace this with the specific feature you built once you review the code.', bullets: ['[Fill in engine feature implemented: UI system, gameplay feature, navigation, file streaming, rendering feature, or debugging tool.]','[Describe technical work: architecture, data flow, event system integration, rendering pipeline changes, or engine subsystem touched.]','[Describe result: demo behavior, performance improvement, workflow improvement, or gameplay capability added.]'], links: [] },
  { title: 'AR Puzzle Prototype', role: 'AR Developer', timeframe: 'Syracuse University', tags: ['AR','Unity','C#','Spatial Interaction','Mobile'], summary: 'Augmented reality puzzle prototype where a cube spawns into physical space and the player moves around it to solve spatial challenges.', bullets: ['Implemented object spawning and real-world interaction using AR plane detection concepts.','Designed puzzle interactions around physical movement, perspective, and spatial reasoning.','Built a prototype focused on accessible controls and readable AR feedback.'], links: [] },
  { title: 'VR Archery Prototype', role: 'VR Developer', timeframe: 'Syracuse University', tags: ['VR','Unity','C#','XR','Interaction Design'], summary: 'Virtual reality bow-and-arrow shooting game focused on embodied input, target feedback, and responsive interaction.', bullets: ['Built core VR interaction loop around aiming, drawing, firing, and target feedback.','Explored motion-based input design and readable player feedback in an immersive environment.','Tuned interaction feel to support quick understanding and repeatable play.'], links: [] },
  { title: 'Distributed Digital Alarm Clock', role: 'C# Developer', timeframe: 'Syracuse University', tags: ['C#','Networking','Desktop App','Systems'], summary: 'C# alarm clock project designed to work across multiple computers. Replace details once you recover the code or assignment prompt.', bullets: ['Built a desktop application with alarm scheduling and time-based event behavior.','[Fill in how multiple computers communicated: sockets, shared storage, client/server model, or other synchronization approach.]','[Fill in reliability or UX details: persistence, notifications, clock sync, error handling, or multi-device behavior.]'], links: [] },
];

const outdoorHighlights = [
  { title: 'USC Climbing Club', role: 'Executive Board Member / Head Trip Lead', timeframe: '2024–Present', tags: ['Leadership','Outdoor Logistics','Risk Management'], summary: 'Lead weekly outdoor climbing trips to areas including Joshua Tree, Bishop, Yosemite, and Red Rocks.', bullets: ['Plan logistics including transportation, gear, safety protocols, and route selection for mixed-ability groups.','Deliver pre-climb safety briefings, mentor newer climbers, and manage group safety in dynamic outdoor environments.'] },
  { title: 'Syracuse University Climbing Wall', role: 'Climbing Wall Staff', timeframe: '2021–2023', tags: ['Instruction','Safety','Equipment'], summary: 'Staffed a high-traffic campus climbing wall and taught climbing safety to new and experienced participants.', bullets: ['Taught belay technique, harness fitting, and climbing safety.','Performed equipment inspections, maintained gear inventory, and enforced facility safety protocols.'] },
  { title: 'Outdoor Climbing', role: 'Boulderer / Trip Leader', timeframe: 'Ongoing', tags: ['Bouldering','Sport Climbing','Mentorship'], summary: 'Experienced climber focused on outdoor bouldering progression, group leadership, and safe technical movement outdoors.', bullets: ['Climbed extensively outdoors and regularly mentor newer climbers in movement, etiquette, and route reading.','Comfortable operating in desert, mountain, and forest environments with changing weather and group needs.'] },
];

const experience = [
  { title:'Game Design Intern / Lead Programmer', org:'IndieCade', timeframe:'May–July 2025', text:'Led gameplay engineering on a climate-focused strategy game and collaborated with a multidisciplinary team to ship a recognized game jam project.' },
  { title:'Night Shift Manager', org:'Copper Beech and Skyler Commons', timeframe:'2023–2024', text:'Managed overnight operations, resident issues, security patrols, conflict de-escalation, and short-term rental turnovers across two properties.' },
  { title:'Climbing Wall Staff', org:'Barnes Center at The Arch, Syracuse University', timeframe:'2021–2023', text:'Supervised climbing wall operations, instructed participants, checked equipment, and maintained safety standards.' },
];
const skills = ['C#','Python','Java','C++','JavaScript','React','HTML/CSS','SQL','Unity 2D/3D','Unreal Engine','Git/GitHub','Perforce','AI Systems','Gameplay Systems','Finite State Machines','Object-Oriented Design','Algorithms','Debugging'];

function ProjectCard({ project }) { return <article className="card project-card"><div className="card-topline"><span>{project.timeframe}</span><span>{project.role}</span></div><h3>{project.title}</h3><p className="summary">{project.summary}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><ul>{project.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul>{project.links?.length > 0 && <div className="links">{project.links.map(link => <a key={link.label} href={link.href}>{link.label} <ArrowUpRight size={15}/></a>)}</div>}</article>; }
function SectionHeader({ icon: Icon, eyebrow, title, children }) { return <div className="section-header"><div className="eyebrow"><Icon size={18}/>{eyebrow}</div><h2>{title}</h2>{children && <p>{children}</p>}</div>; }

export default function App() {
  const [activeFilter, setActiveFilter] = useState('All');
  const filterOptions = ['All', 'Games', 'Software', 'Outdoor'];
  const visibleProjects = useMemo(() => { if (activeFilter === 'Games') return gameProjects; if (activeFilter === 'Software') return softwareProjects; if (activeFilter === 'Outdoor') return outdoorHighlights; return [...gameProjects, ...softwareProjects, ...outdoorHighlights]; }, [activeFilter]);
  return <main>
    <nav className="navbar"><a className="logo" href="#top">AH</a><div className="nav-links"><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div></nav>
    <section id="top" className="hero"><div className="hero-copy"><div className="status-pill"><Sparkles size={16}/> Open to game design, software engineering, and outdoor leadership roles</div><h1>{profile.name}</h1><p className="subtitle">{profile.title}</p><p className="hero-summary">{profile.summary}</p><div className="hero-actions"><a className="button primary" href={`mailto:${profile.email}`}>Contact Me</a><a className="button secondary" href={profile.resumeUrl}>Resume</a></div><div className="social-row"><a href={profile.github}> GitHub</a><a href={profile.linkedin}> LinkedIn</a><span><MapPin size={18}/> {profile.location}</span></div></div>
      <div className="hero-panel"><div className="panel-card"><Gamepad2 size={28}/><h3>Game Projects</h3><p>Gameplay systems, combat, enemy AI, technical design, and rapid prototyping.</p></div><div className="panel-card"><Code2 size={28}/><h3>Software Projects</h3><p>CS coursework, XR prototypes, algorithms, systems, and front-end development.</p></div><div className="panel-card"><Mountain size={28}/><h3>Outdoor Leadership</h3><p>Trip leadership, climbing instruction, logistics, safety, and guest-facing operations.</p></div></div></section>
    <section id="projects" className="section"><SectionHeader icon={BriefcaseBusiness} eyebrow="Portfolio" title="Projects and Leadership">Use the filters to tailor the site toward game applications, general software roles, or outdoor leadership roles.</SectionHeader><div className="filter-row">{filterOptions.map(option => <button key={option} className={activeFilter === option ? 'active' : ''} onClick={() => setActiveFilter(option)} type="button">{option}</button>)}</div><div className="project-grid">{visibleProjects.map(project => <ProjectCard key={`${project.title}-${project.role}`} project={project}/>)}</div></section>
    <section id="experience" className="section split-section"><div><SectionHeader icon={GraduationCap} eyebrow="Background" title="Education">Formal CS foundation with graduate-level game development, AI, algorithms, graphics, and engine coursework.</SectionHeader><div className="card compact-card"><h3>University of Southern California</h3><p>M.S. Computer Science, Game Development · Expected May 2026</p><p>Relevant coursework: Graduate Advanced Game Project, Game Engine Development, Foundations of AI, 3D Graphics and Rendering, Analysis of Algorithms.</p></div><div className="card compact-card"><h3>Syracuse University</h3><p>B.S. Computer Science · Minors in Computer Gaming and Mathematics · Magna Cum Laude</p><p>Relevant coursework: Data Structures, Algorithms, AI, Operating Systems, Systems and Network Programming, Computer Graphics, Virtual Reality, Cryptography.</p></div></div><div><SectionHeader icon={BriefcaseBusiness} eyebrow="Experience" title="Work History"/><div className="timeline">{experience.map(item => <div className="timeline-item" key={`${item.title}-${item.org}`}><span>{item.timeframe}</span><h3>{item.title}</h3><p className="org">{item.org}</p><p>{item.text}</p></div>)}</div></div></section>
    <section id="skills" className="section"><SectionHeader icon={Code2} eyebrow="Tools" title="Technical Skills"/><div className="skill-grid">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></section>
    <section id="contact" className="section contact-section"><div><SectionHeader icon={Mail} eyebrow="Contact" title="Let’s build something."/><p>I’m currently looking for game design, gameplay programming, software engineering, and outdoor leadership opportunities.</p></div><div className="contact-actions"><a className="button primary" href={`mailto:${profile.email}`}>{profile.email}</a><a className="button secondary" href={profile.github}>GitHub</a><a className="button secondary" href={profile.linkedin}>LinkedIn</a></div></section>
  </main>;
}
